### ISSUE TITLE
Double spinners

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/microblog-react#46]
It seems odd to see 2 spinners when refreshing content on a given screen. This is not how refreshing/loading indicators work across most apps, at least on iOS, probably for the reason that refreshing content shouldn’t hide that which is already displayed.

<img src="https://github.com/microdotblog/microblog-react/assets/813383/90665837-07e0-42c1-bdf0-bce878bc8618" alt="Screenshot of timeline screen" width="320">

**Comment by manton** [comment]
Thanks. I think ideally the top spinner would only be used. Usually the top spinner just shows for a second and then the middle loading pane is for the real progress, so they should barely be on the screen at the same time. But good point.

**Comment by vincentritter** [comment]
Two things are happening here.

1. We show a generic "Loading posts..." screen, in the Webview, when loading the content within. This is due to the fact that we cannot, as far as I know, keep a loading spinner going for the "pull to refresh" – it'll only trigger quickly.
2. It also acts as a visual clue that you are, in fact, pulling to refresh.

Normally you shouldn't see both at the same time.

I'm going to close this one for now. But thank you for bringing it up.
